name: ai_assistant
description: "AI Personal Assistant App - Complete Mobile Experience"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  rive: ^0.12.4
  
  # Network & APIs
  dio: ^5.4.0
  retry: ^3.1.2
  connectivity_plus: ^5.0.2
  
  # AI & ML
  google_generative_ai: ^0.2.2
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Authentication & Security
  crypto: ^3.0.3
  bcrypt: ^1.1.3
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  
  # Communication
  mailer: ^6.0.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  
  # Media & Files
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  camera: ^0.10.5+7
  video_player: ^2.8.1
  audioplayers: ^5.2.1
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3
  
  # Additional Features
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  weather: ^3.1.1
  http: ^1.1.2
  webview_flutter: ^4.4.4
  flutter_local_notifications: ^16.3.0
  workmanager: ^0.5.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/audio/
    - assets/icons/
    - assets/avatars/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
